# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet publish --configuration $(buildConfiguration)
  displayName: 'dotnet publish $(buildConfiguration)'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'master-artifact' 
    targetPath: $(Build.Repository.LocalPath)/myB2B.Web/bin/Release/netcoreapp2.2/publish/
